# Generated by Django 5.2.5 on 2025-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_subcategory_unique_together_category_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'governorate')},
        ),
        migrations.AddField(
            model_name='area',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='style',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='style',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'governorate'), ('name_ar', 'governorate'), ('name_en', 'governorate')},
        ),
    ]
