# Generated by Django 5.2.5 on 2025-12-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_area_unique_together_area_name_ar_area_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_normalized',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_normalized',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
