# Generated by Django 5.2.5 on 2025-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_product_description_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_ar_normalized',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_normalized',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
