# Generated by Django 5.2.5 on 2026-02-16 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/backgrounds/'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promobanner',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/artworks/'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/artworks/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
