# Generated by Django 5.2.5 on 2026-02-19 09:18

import django.db.models.deletion
from django.db import migrations, models


def clean_favorites(apps, schema_editor):
    try:
        Favorite = apps.get_model('users', 'Favorite')
        Favorite.objects.all().delete()
    except LookupError:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0021_address_is_active_address_quantity_address_views_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),

        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='styles',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RunPython(clean_favorites),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),

        migrations.RemoveField(
            model_name='review',
            name='user',
        ),

        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='address',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='address',
            name='views',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
