# Generated by Django 5.2.5 on 2026-02-20 19:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='total_orders',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated LTV metric (can factor returns/discounts)', max_digits=12),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, help_text='Incremented atomically via OrderCreatedEvent'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='region_snapshot',
            field=models.CharField(blank=True, help_text='Last known region from the most recent order', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot-aggregated total from delivered orders', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user'], name='crm_custome_user_id_c84681_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['total_spent'], name='crm_custome_total_s_791066_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['region_snapshot'], name='crm_custome_region__60cc04_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['created_at'], name='crm_custome_created_6dcef1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['-total_spent'], name='crm_custome_total_s_1b9e4a_idx'),
        ),
    ]
