# Generated by Django 5.2.5 on 2026-02-20 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productspecification_productspecificationvalue_and_more'),
        ('tracking', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartevent',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addtocartevent',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutevent',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productviewevent',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistevent',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlistevent',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtocartevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='addtocartevent',
            name='session_id',
            field=models.CharField(db_index=True, default='default_session', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtocartevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='session_id',
            field=models.CharField(db_index=True, default='default_session', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productviewevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productviewevent',
            name='session_id',
            field=models.CharField(db_index=True, default='default_session', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productviewevent',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productviewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlistevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='addtocartevent',
            index=models.Index(fields=['created_at'], name='tracking_ad_created_24fc90_idx'),
        ),
        migrations.AddIndex(
            model_name='addtocartevent',
            index=models.Index(fields=['vendor', 'created_at'], name='tracking_ad_vendor__ca3480_idx'),
        ),
        migrations.AddIndex(
            model_name='addtocartevent',
            index=models.Index(fields=['session_id'], name='tracking_ad_session_9df06f_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutevent',
            index=models.Index(fields=['created_at'], name='tracking_ch_created_b9e38a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutevent',
            index=models.Index(fields=['session_id'], name='tracking_ch_session_937416_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewevent',
            index=models.Index(fields=['created_at'], name='tracking_pr_created_fac712_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewevent',
            index=models.Index(fields=['vendor', 'created_at'], name='tracking_pr_vendor__bb790e_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewevent',
            index=models.Index(fields=['session_id'], name='tracking_pr_session_ad14e6_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistevent',
            index=models.Index(fields=['created_at'], name='tracking_wi_created_de6bca_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistevent',
            index=models.Index(fields=['vendor', 'created_at'], name='tracking_wi_vendor__0c8ca6_idx'),
        ),
    ]
