# Generated by Django 5.2.5 on 2026-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
