# Generated by Django 5.2.5 on 2026-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_code_used_order_final_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_code_used',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot of coupon code used at checkout', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
