# Generated by Django 5.2.5 on 2026-02-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productspecification_productspecificationvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='views_count',
        ),
    ]
